spring.application.name=youtubedemo

# YouTube API Configuration
youtube.api.key=AIzaSyC1XmiWPTXowOMJ-OxRR4VsF7xVVIPV0e0

# Server Configuration
server.port=8081

# Thymeleaf Configuration
spring.thymeleaf.cache=false
